version: '3.3'

services:

  mongo-db:
    container_name: mongo-db
    image: mongo:3.5
    ports:
      - 27017:27017
    networks:
      - default

  postgress-db:
    container_name: postgress-db
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxdb
